- XAMLTest.Tests/VisualElementTests.cs
- XAMLTest/VisualTreeService.cs
Set or get the property with null value causes exception.
> Fixed to access a property with null value correctly

- XAMLTest.Tests/Simulators/App.cs
- XAMLTest.Tests/Simulators/Image.cs
- XAMLTest.Tests/TestRecorderTests.cs
- XAMLTest/TestRecorder.cs
Added unit tests for SaveScreenshot
Fixes #15
> Allow saving screenshot with provided suffix.

- .github/workflows/dotnet-core.yml
- Directory.Build.props
- XAMLTest.TestApp/MainWindow.xaml
- XAMLTest.TestApp/XAMLTest.TestApp.csproj
- XAMLTest.Tests/TestControls/TextBox_ValidationError.xaml
- XAMLTest.Tests/TestRecorderTests.cs
- XAMLTest.Tests/VisualElementTests.cs
- XAMLTest.Tests/XAMLTest.Tests.csproj
- XAMLTest/App.cs
- XAMLTest/AppMixins.cs
- XAMLTest/Client.cs
- XAMLTest/IValue.cs
- XAMLTest/Input/KeyboardInput.cs
- XAMLTest/Internal/App.cs
- XAMLTest/Internal/BaseValue.cs
- XAMLTest/Internal/EventRegistration.cs
- XAMLTest/Internal/ManagedApp.cs
- XAMLTest/Internal/VisualElement.cs
- XAMLTest/Server.cs
- XAMLTest/TestRecorder.cs
- XAMLTest/Utility/AppDomainMixins.cs
- XAMLTest/VisualElementMixins.FrameworkElement.cs
- XAMLTest/VisualElementMixins.UIElement.cs
- XAMLTest/VisualElementMixins.cs
- XAMLTest/VisualTreeService.cs
- XAMLTest/WindowMixins.cs
- XAMLTest/XAMLTest.csproj
This is slightly more generic as it allows for property expression matching as well.
> Adding automation Id support

- XAMLTest.Tests/VisualElementTests.cs
- XAMLTest/VisualTreeService.cs
When an element is rotated the wrong coordinates were causing an exception.
> Get coordinates bug

- XAMLTest.Tests/VisualElementTests.cs
- XAMLTest/VisualTreeService.cs
> Allow query types using base type names.

- XAMLTest/App.cs
- XAMLTest/Program.cs
> Adding heartbeat timer.

- XAMLTest.Tests/GetResourceTests.cs
- XAMLTest/App.cs
- XAMLTest/Event/EventRegistrar.cs
- XAMLTest/Host/VisualTreeService.cs
- XAMLTest/Internal/App.cs
- XAMLTest/Internal/EventRegistration.cs
- XAMLTest/Internal/VisualElement.cs
- XAMLTest/Wait.cs
- XAMLTest/XAMLTestException.cs
Updated all exception usages.
Fixes #7
> Adding XAMLTestException

- XAMLTest.Tests/AppTests.cs
- XAMLTest.Tests/GetResourceTests.cs
- XAMLTest.Tests/Simulators/App.cs
- XAMLTest.Tests/TestRecorderTests.cs
- XAMLTest/Host/VisualTreeService.cs
> GetScreenshot now properly captures the screen the window is on

- .github/workflows/dotnet-core.yml
- XAMLTest.Tests/AppTests.cs
- XAMLTest.Tests/TestRecorderTests.cs
- XAMLTest/Program.cs
- XAMLTest/TestRecorder.cs
Removing screen resolution setter
> Fix warnings

- XAMLTest.Tests/TestRecorderTests.cs
- XAMLTest/TestRecorder.cs
> Adding suffix parameter to test recorder

- XAMLTest.Tests/SendMouseInputTests.cs
- XAMLTest/Input/MouseInput.cs
- XAMLTest/VisualElementMixins.Input.cs
> Adding convenience offset to click methods

- XAMLTest.TestApp/XAMLTest.TestApp.csproj
- XAMLTest.Tests/AppTests.cs
- XAMLTest.Tests/GetCoordinatesTests.cs
- XAMLTest.Tests/GetEffectiveBackgroundTests.cs
- XAMLTest.Tests/GetResourceTests.cs
- XAMLTest.Tests/SendKeyboardInputTests.cs
- XAMLTest.Tests/SendMouseInputTests.cs
- XAMLTest.Tests/SerializerTests.cs
- XAMLTest.Tests/TestRecorderTests.cs
- XAMLTest.Tests/VisualElementTests.cs
- XAMLTest.UnitTestGenerator/UnitTestGenerator.cs
- XAMLTest/App.cs
- XAMLTest/AppOptions.cs
- XAMLTest/Host/VisualTreeService.cs
- XAMLTest/IVersion.cs
- XAMLTest/Internal/App.cs
- XAMLTest/Internal/Version.cs
- XAMLTest/XAMLTest.csproj
Adding in version information.
Updates the API for StartRemote (BREAKING CHANGE)
> Awaiting all of the calls

- XAMLTest.Tests/HighlightTests.cs
- XAMLTest/HighlightConfig.cs
- XAMLTest/Host/VisualTreeService.Events.cs
- XAMLTest/Host/VisualTreeService.Highlight.cs
- XAMLTest/Host/VisualTreeService.Input.cs
- XAMLTest/Host/VisualTreeService.Invocation.cs
- XAMLTest/Host/VisualTreeService.cs
- XAMLTest/Host/XamlTestSpec.proto
- XAMLTest/ISerializer.cs
- XAMLTest/IVisualElement.cs
- XAMLTest/Internal/SelectionAdorner.cs
- XAMLTest/Internal/Serializer.cs
- XAMLTest/Internal/VisualElement.cs
- XAMLTest/VisualElementMixins.Highlight.cs
This adds in a new Highlight functionality
Fixes #56
> Adding method to show coordinates of elements

- XAMLTest.Tests/PositionTests.cs
- XAMLTest.Tests/TestControls/MouseClickPositions.xaml
- XAMLTest.Tests/TestControls/MouseClickPositions.xaml.cs
- XAMLTest/Host/VisualTreeService.Input.cs
- XAMLTest/Position.cs
> Expanding position enum

- XAMLTest.TestApp/MainWindow.xaml
- XAMLTest.TestApp/XAMLTest.TestApp.csproj
- XAMLTest.Tests/AppTests.cs
- XAMLTest.Tests/GetCoordinatesTests.cs
- XAMLTest.Tests/GetEffectiveBackgroundTests.cs
- XAMLTest.Tests/Simulators/App.cs
- XAMLTest/Host/VisualTreeService.cs
- XAMLTest/Host/XamlTestSpec.proto
- XAMLTest/IApp.cs
- XAMLTest/IVisualElement.cs
- XAMLTest/Internal/App.cs
- XAMLTest/Internal/AppContext.cs
- XAMLTest/Internal/BaseValue.cs
- XAMLTest/Internal/Property.cs
- XAMLTest/Internal/Resource.cs
- XAMLTest/Internal/Serializer.cs
- XAMLTest/Internal/VisualElement.cs
- XAMLTest/Internal/Window.cs
- XAMLTest/Transport/XamlSegmentSerializer.cs
- XAMLTest/Types.cs
- XAMLTest/VisualElementMixins.Window.cs
- XAMLTest/XAMLTest.csproj
- XAMLTest/XamlSegment.cs
- XAMLTest/XmlNamespace.cs
- XAMLTest/XmlNamespaceMixins.cs
> Allowing setting XML namespaces on content.

- Directory.Build.props
- XAMLTest.Generator/ElementGenerator.cs
- XAMLTest.TestApp/App.xaml.cs
- XAMLTest.Tests/AppTests.cs
- XAMLTest.UnitTestGenerator/UnitTestGenerator.cs
- XAMLTest/App.cs
- XAMLTest/AppOptions.cs
- XAMLTest/Host/VisualTreeService.Invocation.cs
- XAMLTest/Host/VisualTreeService.cs
- XAMLTest/IVisualElement.cs
- XAMLTest/Internal/App.cs
- XAMLTest/Logger.cs
- XAMLTest/Program.cs
- XAMLTest/VisualElementMixins.RemoteExecute.cs
> Adding support for custom Application classes

- .github/workflows/dotnet-core.yml
- XAMLTest/Transport/DpiScaleSerializer.cs
- XAMLTest/XAMLTest.csproj
> Fixing warnings

- XAMLTest.Tests/SendKeyboardInputTests.cs
- XAMLTest/IVisualElement.cs
- XAMLTest/Input/KeyboardInput.cs
- XAMLTest/Input/KeysInput.cs
- XAMLTest/Input/ModifiersInput.cs
- XAMLTest/KeyboardInput.cs
Adding a Thread.Sleep to better match SendKeys.
> Minor code clean up

- XAMLTest/Host/VisualTreeService.Elements.cs
- XAMLTest/Host/VisualTreeService.Input.cs
- XAMLTest/Host/VisualTreeService.cs
> Added additional check for child windows that may have focus

- .github/workflows/dotnet-core.yml
- Directory.Build.props
- Directory.Packages.props
- XAMLTest.Generator/XAMLTest.Generator.csproj
- XAMLTest.TestApp/XAMLTest.TestApp.csproj
- XAMLTest.Tests/AppTests.cs
- XAMLTest.Tests/ValidationTests.cs
- XAMLTest.Tests/XAMLTest.Tests.csproj
- XAMLTest.UnitTestGenerator/XAMLTest.UnitTestGenerator.csproj
- XAMLTest.sln
- XAMLTest/App.cs
- XAMLTest/AppOptions.cs
- XAMLTest/Host/VisualTreeService.Events.cs
- XAMLTest/IVisualElement.cs
- XAMLTest/NativeMethods.txt
- XAMLTest/VisualElementMixins.Input.cs
- XAMLTest/XAMLTest.csproj
- XAMLTest/XAMLTestException.cs
Adding support for minimizing all windows
Updates to NuGet packages
Adding .NET 8
Fixing some spelling errors.
> Lots of clean up

- XAMLTest.Generator/ElementGenerator.cs
- XAMLTest.Tests/GeneratorTests.cs
This should resolve the problems with testing https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit/pull/3661
> Fixing issue with a genric base class.

- XAMLTest.Tests/AppTests.cs
- XAMLTest.Tests/SendMouseInputTests.cs
- XAMLTest.Tests/Simulators/App.cs
- XAMLTest/AppMixins.RemoteExecute.cs
- XAMLTest/AppMixins.cs
- XAMLTest/Host/VisualTreeService.Invocation.cs
- XAMLTest/Host/XamlTestSpec.proto
- XAMLTest/IApp.cs
- XAMLTest/IVisualElement.cs
- XAMLTest/Internal/App.cs
- XAMLTest/Internal/ProtocolClientMixins.cs
- XAMLTest/Internal/VisualElement.cs
- XAMLTest/VisualElementMixins.RemoteExecute.cs
Adds RemoteExecute methods to IApp and IVisualElement
to execute delegates in the remote app domain.
This allows for more complex interactions with the UI
and application state during testing.
> Adds RemoteExecute support to IApp

- XAMLTest.Tests/VisualElementTests.cs
- XAMLTest/AppMixins.RemoteExecute.cs
- XAMLTest/Host/VisualTreeService.Invocation.cs
- XAMLTest/VisualElementMixins.RemoteExecute.cs
Allows remote execution of asynchronous methods, including those with and without return values.
Updates the invocation logic to handle Task and Task<T> return types.
Adds corresponding unit tests to verify the new functionality.
> Enables remote execution of async methods
